// Run: node test_guided_web.js. No network, saved settings or game files are used.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('web/app.js','utf8'),html=fs.readFileSync('web/index.html','utf8'),nodes=new Map(),calls=[],scrolls=[],focuses=[];
const node=id=>{if(!nodes.has(id)){let value='';const classes=new Set();nodes.set(id,{id,get value(){return value;},set value(next){value=String(next);},checked:false,innerHTML:'',textContent:'',hidden:false,disabled:false,classList:{toggle(name,enabled){if(enabled)classes.add(name);else classes.delete(name);},contains(name){return classes.has(name);}},close(){},scrollIntoView(options){scrolls.push([id,JSON.parse(JSON.stringify(options))]);},querySelector(selector){return node(id+' '+selector);},focus(options){focuses.push([id,JSON.parse(JSON.stringify(options))]);},closest(){return node(id+'-label');},addEventListener(event,handler){this[event]=handler;}});}return nodes.get(id);};
function actionCard(id,number,status,description){
  const card=node(id),statusLabel={done:'Complete',action:'Needs action',waiting:'Upcoming'}[status];
  assert.equal(card.classList.contains('guided-step'),true,'the existing action button is also the progress card');
  for(const name of ['done','action','waiting'])assert.equal(card.classList.contains(name),name===status,'a card has one visual progress state');
  assert.match(card.innerHTML,new RegExp(`class="guided-step-marker" aria-hidden="true">${status==='done'?'✓':number}</span>`));
  assert.match(card.innerHTML,/<span class="deck-action-copy"><strong>[^<]+<\/strong><span>/,'the action and explanation share the clickable card');
  assert.match(card.innerHTML,description);
  assert.match(card.innerHTML,new RegExp(`<span class="sr-only">${statusLabel}</span>`),'progress is also announced to screen readers');
}
let review,profileResult,previewResult,syncOptionsResult,deckUiActive=false,protonResult={configured:false,loader_installed:false,prefix:'/fixture/prefix'};
const settings={host:'192.0.2.50',user:'deck',port:22,key:'',game_path:'/fixture/game',workshop_path:'/fixture/workshop'};
const state={profiles:[{id:'p1',name:'Shared <profile>',mod_count:2,enabled_count:2}],mods:[],downloads:[],settings:{deck:settings},loader_installed:true,nexus_connected:true,deck_connection:{connected:true,host:settings.host,user:'deck'}};
const context=vm.createContext({$:node,state,comparison:null,working:false,pendingFocus:null,activeDownloadStates:new Set(['starting','waiting','downloading','verifying','installing','awaiting_review']),toast(){},work:async(_,task)=>task(),refresh:async()=>{if(deckUiActive)vm.runInContext('renderDeckConnection()',context);},renderUpdates(){},pollDownloads:async()=>{},
  modal(...args){review=args;node('dialog-actions').lastElementChild={disabled:!!args[2].at(-1)?.[3]};},
  api:async(action,body)=>{calls.push([action,body===undefined?undefined:JSON.parse(JSON.stringify(body))]);
    if(action==='profile-compare'){if(profileResult instanceof Error)throw profileResult;return profileResult;}
    if(action==='steam-workshop')return {message:'Subscribe in Steam'};
    if(action==='profile-apply')return {pending:['Workshop <mod>'],warnings:['Approval needed for Workshop <mod>']};
    if(action==='launch')return {message:'Game launched for Workshop approval'};
    if(action==='deck-preview'){if(previewResult instanceof Error)throw previewResult;return previewResult;}
    if(action==='deck-sync-options'){if(syncOptionsResult instanceof Error)throw syncOptionsResult;const result=syncOptionsResult?await syncOptionsResult:{options:body.options};state.settings.deck_sync_options=result.options;return result;}
    if(action==='deck-proton-status'){if(protonResult instanceof Error)throw protonResult;return protonResult;}
    if(action==='deck-proton-setup'){protonResult={configured:true,loader_installed:false,prefix:'/fixture/prefix',backup:'/fixture/backup.reg'};return protonResult;}
    if(action==='deck-sync'){protonResult={...protonResult,loader_installed:true};return {parity:true,verified_files:3,backups:['/fixture/backup'],counts:{files:3}};}
    if(action==='deck-connect'){assert.equal(node('deck-password').value,'');state.settings.deck={...body.deck};state.deck_connection={connected:true,host:body.deck.host,user:body.deck.user};return {deck:body.deck,discovery:{found:true}};}
    throw Error('Unexpected request: '+action);
  }});
const run=code=>vm.runInContext(code,context);
run(source.slice(source.indexOf('const escapeHTML'),source.indexOf('function toast')));
run(source.slice(source.indexOf('function focusAfterWork'),source.indexOf('function page(')));
run(source.slice(source.indexOf("let selectedProfile='"),source.indexOf('async function stagePath')));
run(source.slice(source.indexOf('function compareView'),source.indexOf('async function fullDeckGuide')));
run(source.slice(source.indexOf("$('profile-create').onclick"),source.indexOf("$('setup').onclick")));
run('deckFieldsFill(state.settings.deck)');

(async()=>{
  profileResult={id:'p1',name:'Shared <profile>',token:'fresh-review',entries:[{key:'steam:123',name:'Workshop <mod>',workshop_id:'123',enabled:true,status:'missing',version:'1.0'},
    {key:'nexus:12',name:'Nexus <mod>',nexus_mod_id:12,enabled:true,status:'installed',version:'1.0',installed_version:'2.0',version_mismatch:true}],
    blockers:['Install Workshop <mod>'],mismatches:[{name:'Nexus <mod>',version:'1.0',installed_version:'2.0'}],changes:[]};
  const savedProfiles=state.profiles;state.profiles=[];run('renderProfiles()');
  assert.equal(node('profile-selection').hidden,true);assert.equal(node('profile-workflow').hidden,true);assert.equal(node('profile-options').hidden,true);
  assert.match(node('profile-entries').innerHTML,/Your first profile/);
  for(const id of ['profile-refresh','profile-install','profile-apply'])assert.equal(node(id).disabled,true,'no profile means no workflow action is unlocked');
  state.profiles=savedProfiles;run('renderProfiles()');
  actionCard('profile-refresh',1,'action',/Compare this profile with installed mods/);
  actionCard('profile-install',2,'waiting',/Unlocks after checking mods/);
  actionCard('profile-apply',3,'waiting',/Check mods first/);
  assert.equal(node('profile-install').disabled,true);assert.equal(node('profile-apply').disabled,true,'unchecked profiles cannot be applied');
  await run('compareProfile()');
  actionCard('profile-refresh',1,'done',/2 profile mods checked/);
  actionCard('profile-install',2,'action',/1 missing · review highlighted mods/);
  actionCard('profile-apply',3,'waiting',/Get the required mods ready first/);
  assert.equal(node('profile-apply').disabled,true,'missing required mods lock the top Apply card');
  const beforeReveal=calls.length;await node('profile-install').onclick();
  assert.deepEqual(scrolls.at(-1),['profile-entries .guided-action',{block:'nearest',behavior:'instant'}]);
  assert.equal(focuses.at(-1)[0],'profile-entries .guided-action');assert.equal(calls.length,beforeReveal,'Get mods ready reveals per-mod choices without starting installs');
  run('profileLoading=true;renderProfiles()');
  for(const id of ['profile-refresh','profile-install','profile-apply'])assert.equal(node(id).disabled,true,'loading clears previously enabled actions');
  actionCard('profile-refresh',1,'waiting',/Checking installed mods/);
  run('profileLoading=false;profileError="Check <failed>";renderProfiles()');
  actionCard('profile-refresh',1,'action',/Check failed · try again/);
  assert.equal(node('profile-install').disabled,true);assert.equal(node('profile-apply').disabled,true,'failed comparison clears old downstream gates');
  assert.match(node('profile-entries').innerHTML,/Check &lt;failed&gt;/);run('profileError="";renderProfiles()');
  assert.doesNotMatch(node('profile-entries').innerHTML,/guided-checklist|data-profile-review|data-profile-refresh/,'per-mod results contain no passive or duplicate workflow');
  assert.match(node('profile-entries').innerHTML,/Workshop &lt;mod&gt;/);
  await run('openProfileWorkshop("123")');
  assert.match(node('profile-refresh').innerHTML,/<strong>Refresh Steam mods<\/strong>/);
  actionCard('profile-refresh',1,'action',/Finish Steam Downloads, then check here/);
  assert.equal(calls.filter(([action])=>action==='profile-apply').length,0,'opening Steam never applies a profile');
  await run('reviewProfile()');
  assert.ok(review[2].at(-1)[3],'blockers disable apply even with version choices');
  node('profile-accept-versions').checked=true;node('profile-accept-versions').change();
  assert.equal(node('dialog-actions').lastElementChild.disabled,true);
  profileResult.entries[0].status='installed';profileResult.blockers=[];
  await run('compareProfile()');assert.doesNotMatch(node('profile-entries').innerHTML,/Waiting for Steam/);
  actionCard('profile-install',2,'action',/1 release differences · review below/);
  assert.equal(node('profile-install').disabled,false,'release differences remain reachable even with no missing mod');
  assert.equal(node('profile-apply').disabled,false,'version differences can be reviewed for explicit acceptance');
  for(const stateName of ['downloading','awaiting_review','waiting_game']){
    state.downloads=[{id:'fixture-download',state:stateName}];run('renderProfiles()');
    assert.equal(node('profile-apply').disabled,true,stateName+' prevents applying or launching through the workflow');
    actionCard('profile-apply',3,'waiting',/Finish the current download first/);
  }
  state.downloads=[];run('renderProfiles()');
  await run('reviewProfile()');assert.equal(node('dialog-actions').lastElementChild.disabled,true,'version differences need explicit acceptance');
  node('profile-accept-versions').checked=true;node('profile-accept-versions').change();
  assert.equal(node('dialog-actions').lastElementChild.disabled,false);
  await review[2].at(-1)[1]();
  assert.deepEqual(calls.find(([action])=>action==='profile-apply')[1],{id:'p1',token:'fresh-review',accept_versions:true});
  assert.match(review[1],/Launch the game and approve/);assert.match(review[1],/Workshop &lt;mod&gt;/);
  assert.ok(review[2].some(([label])=>label==='Launch game to approve'),'completion offers the actual next step');
  actionCard('profile-install',2,'done',/You accepted the installed releases/);
  actionCard('profile-apply',3,'action',/Approve Workshop mods in the game/);
  assert.match(node('profile-apply').innerHTML,/<strong>Launch to approve<\/strong>/);
  const appliedCount=calls.filter(([action])=>action==='profile-apply').length;await node('profile-apply').onclick();
  assert.equal(calls.at(-1)[0],'launch','the same top Apply card becomes the approval launch action');
  assert.equal(calls.filter(([action])=>action==='profile-apply').length,appliedCount,'Workshop approval launch never applies again');
  profileResult.changes=[{name:'Workshop <mod>',enabled:true}];await run('compareProfile()');
  assert.match(node('profile-entries').innerHTML,/Profile applied · Workshop approval needed/,'pending loader approval keeps the completion panel visible even while enabled=false');
  state.mods=[{name:'Workshop <mod>',workshop_id:'123',enabled:true}];profileResult.changes=[];await run('compareProfile()');
  actionCard('profile-apply',3,'done',/Enabled states match this profile/);
  assert.equal(node('profile-apply').disabled,true,'a refresh completes approval and prevents redundant application');
  assert.doesNotMatch(node('profile-apply').innerHTML,/Launch to approve/,'a refresh clears the launch step once Workshop is enabled');
  profileResult.changes=[{name:'Nexus <mod>',enabled:false}];await run('compareProfile()');
  assert.doesNotMatch(node('profile-entries').innerHTML,/class="guided-result/,'later mod-state changes require another review instead of claiming the profile still matches');
  actionCard('profile-apply',3,'action',/Review releases and enabled state changes/);
  const profilePage=html.match(/<section id="page-profiles"[\s\S]*?<\/section>/)[0];
  for(const id of ['profile-create','profile-import','profile-refresh','profile-install','profile-apply'])assert.equal((profilePage.match(new RegExp(`id="${id}"`,'g')) || []).length,1,'profile workflow controls have one static button each');
  const profileWorkflow=profilePage.match(/<div class="profile-main-actions"[^>]*>([\s\S]*?)<\/div>/)[1];
  assert.deepEqual([...profileWorkflow.matchAll(/<button\b[^>]*\bid="([^"]+)"/g)].map(match=>match[1]),['profile-refresh','profile-install','profile-apply'],'profile action cards follow Check → Get mods ready → Review');
  assert.doesNotMatch(profilePage,/id="profile-name"/,'the name field belongs to the New profile modal');
  assert.match(profilePage,/<details id="profile-options"[^>]*><summary>/,'sharing and destructive options are folded by default');

  state.settings.deck_sync_options={mods:false,configs:true,approvals:false,loader:false,game_settings:true};run('deckSyncOptions=null;renderDeckSyncOptions()');
  assert.equal(node('deck-sync-mods').checked,false);assert.equal(node('deck-sync-configs').checked,true);assert.equal(node('deck-sync-game_settings').checked,true,'saved choices initialize the controls');
  state.settings.deck_sync_options=undefined;run('deckSyncOptions=null;renderDeckSyncOptions()');
  for(const key of ['mods','configs','approvals','loader'])assert.equal(node('deck-sync-'+key).checked,true,'existing installs retain the previous complete-mod-sync default');
  assert.equal(node('deck-sync-game_settings').checked,false,'game preferences remain opt-in');
  deckUiActive=true;state.deck_connection.connected=false;state.settings.deck={...settings,host:''};
  run('deckFieldsFill(state.settings.deck);deckSettingsInitialized=false;renderDeckConnection()');
  assert.equal(node('deck-settings').open,true,'first-time connection details start expanded');
  assert.equal(node('deck-setup-guide').hidden,false,'incomplete setup has a prominent guide');
  for(const id of ['deck-preview','deck-proton-setup','sync-now'])assert.equal(node(id).disabled,true,'only Connect starts unlocked');
  actionCard('deck-connect',1,'action',/Enter your Deck address and password/);
  actionCard('deck-preview',2,'waiting',/Verify game versions and review selected files/);
  actionCard('deck-proton-setup',3,'waiting',/Unlocks after a matching comparison/);
  actionCard('sync-now',4,'waiting',/Back up, copy selected files and verify hashes/);
  assert.equal(node('deck-proton-info').hidden,true,'BepInEx details stay out of the way before installation is ready');
  state.settings.deck={...settings};run('deckFieldsFill(state.settings.deck);deckSettingsInitialized=false;renderDeckConnection()');
  assert.equal(node('deck-settings').open,false,'saved connection details initialize collapsed');
  node('deck-settings').open=true;run('renderDeckConnection()');
  assert.equal(node('deck-settings').open,true,'manual disclosure expansion survives an ordinary render');
  node('deck-password').value='dummy';await run('connectDeck(deckFields(),undefined,{password:"dummy",remember_password:false})');
  assert.equal(node('deck-settings').open,false,'successful connection with discovered folders collapses settings');
  assert.ok(calls.some(([action])=>action==='deck-proton-status'),'connection checks loader readiness read-only');
  assert.ok(!calls.some(([action])=>action==='deck-proton-setup'),'connect does not write Proton setup automatically');
  assert.equal(node('deck-preview').disabled,false);assert.equal(node('deck-proton-setup').disabled,true,'Compare unlocks installation');
  actionCard('deck-connect',1,'done',/Deck connected · game folders found/);
  actionCard('deck-preview',2,'action',/Verify game versions and review selected files/);
  const beforeEarlyActions=calls.length;await assert.rejects(run('configureDeckProton(true)'),/Compare matching game versions/);
  await assert.rejects(run('syncDeck()'),/compare your Deck/);assert.equal(calls.length,beforeEarlyActions,'out-of-order helper calls cannot reach writing APIs');
  node('deck-workshop_path').value='';run('renderDeckConnection()');assert.equal(node('deck-preview').disabled,true,'missing folders block comparison');
  node('deck-workshop_path').value=settings.workshop_path;
  previewResult={digest:'before-install',game_version:{matched:true,build_id:'12345'},counts:{additions:1,changes:1,extras:1,local_files:3},additions:['new.dll'],changes:['changed.dll'],extras:['extra.dll'],unsupported:[],warnings:[]};
  await run('compareDeck()');
  assert.deepEqual(scrolls.at(-1),['deck-comparison',{block:'start',behavior:'instant'}],'a comparison reveals its result card after refresh');
  assert.equal(focuses.at(-1)[0],'deck-comparison h2');
  assert.equal(node('deck-proton-setup').disabled,false,'a matching build and known incomplete loader status unlock installation');
  assert.equal(node('sync-now').disabled,true,'Sync stays locked until loading is configured');
  actionCard('deck-preview',2,'done',/Same Steam build 12345/);
  actionCard('deck-proton-setup',3,'action',/Prepare the Proton loading setting/);
  actionCard('sync-now',4,'waiting',/1 new · 1 changed · 1 extras/);
  assert.equal(node('deck-proton-info').hidden,false,'installation details appear beneath actionable installation');
  run('deckProtonState={loading:true};renderDeckProton()');assert.equal(node('deck-proton-setup').disabled,true);
  run('resetDeckProton();renderDeckProton()');assert.equal(node('deck-proton-setup').disabled,true,'unknown setup status cannot unlock installation');
  protonResult=Error('Launch the game once through Proton.');await run('compareDeck()');
  assert.equal(node('deck-proton-setup').disabled,true,'a failed loader status check keeps installation locked');
  assert.equal(node('sync-now').disabled,true);assert.equal(node('deck-proton-info').hidden,true);
  actionCard('deck-proton-setup',3,'waiting',/Setup check needs attention/);
  assert.match(node('deck-status').textContent,/check needs attention/,'the actionable check error is shown beside the grouped controls');
  run('working=true');previewResult=Error('Game versions differ: PC 12345, Deck 11111.');
  const beforeErrorFocus=focuses.length;await assert.rejects(run('compareDeck()'),/versions differ/);
  assert.equal(scrolls.at(-1)[0],'deck-comparison','mismatch results are brought into view too');
  assert.equal(focuses.length,beforeErrorFocus,'inert controls are not focused during work');
  assert.equal(context.pendingFocus,node('deck-comparison h2'),'the heading is queued for focus after work clears');
  assert.equal(node('deck-proton-setup').disabled,true);assert.equal(node('sync-now').disabled,true,'mismatched versions lock the remaining steps');
  actionCard('deck-preview',2,'action',/Comparison stopped · see the message below/);
  run('working=false;pendingFocus.focus({preventScroll:true});pendingFocus=null');
  protonResult={configured:false,loader_installed:false,prefix:'/fixture/prefix'};
  previewResult={digest:'before-install',game_version:{matched:true,build_id:'12345'},counts:{additions:1,changes:1,extras:1,local_files:3},additions:['new.dll'],changes:['changed.dll'],extras:['extra.dll'],unsupported:[],warnings:[]};await run('compareDeck()');
  const beforeInstall=calls.length;previewResult={...previewResult,digest:'after-install'};await run('configureDeckProton(true)');
  const installCalls=calls.slice(beforeInstall).map(([action])=>action);
  assert.equal(installCalls[0],'deck-proton-setup');assert.ok(installCalls.includes('deck-preview'),'configuring Proton refreshes the invalidated preview');
  assert.equal(context.comparison.digest,'after-install');assert.equal(node('sync-now').disabled,false,'configured loading permits sync to supply missing loader DLLs');
  assert.equal(node('deck-proton-setup').disabled,true);assert.equal(node('deck-proton-info').hidden,true,'completed loading setup hides its instructions');
  actionCard('deck-proton-setup',3,'done',/Loading configured · files copied during sync/);
  actionCard('sync-now',4,'action',/1 new · 1 changed · 1 extras/);
  assert.equal(node('deck-setup-guide').hidden,false,'the guide stays visible until missing loader files are supplied');
  state.loader_installed=false;run('renderDeckConnection()');assert.equal(node('sync-now').disabled,true,'PC foundation is required before copying it');
  assert.match(node('deck-status').textContent,/Install BepInEx on your PC/);state.loader_installed=true;run('renderDeckConnection()');
  await run('syncDeck()');assert.deepEqual(calls.find(([action])=>action==='deck-sync')[1],{digest:'after-install',options:{mods:true,configs:true,approvals:true,loader:true,game_settings:false}},'sync uses the newly verified digest and selected scope');
  assert.equal(scrolls.at(-1)[0],'deck-comparison','sync completion reveals its result card');
  assert.equal(focuses.at(-1)[0],'deck-comparison h2');
  const beforeOrdinaryRefresh=scrolls.length;run('renderDeckConnection()');await context.refresh();
  assert.equal(scrolls.length,beforeOrdinaryRefresh,'ordinary refreshes preserve scroll');
  assert.match(node('deck-comparison').innerHTML,/Sync complete · selected setup matches/);
  assert.match(node('deck-comparison').innerHTML,/<details[^>]*><summary>Sync details & backups<\/summary><pre>/,'technical JSON stays folded');
  actionCard('deck-preview',2,'done',/Same Steam build 12345/);
  actionCard('deck-proton-setup',3,'done',/Loader files and Proton setting detected/);
  actionCard('sync-now',4,'done',/Selected setup matches/);
  assert.equal(node('sync-now').disabled,true,'completed historical plans cannot be synced again');
  assert.equal(node('deck-setup-guide').hidden,true,'a connected fully prepared Deck hides the prominent setup prompt');
  const beforeRepeatSync=calls.length;await assert.rejects(run('syncDeck()'),/compare your Deck/);assert.equal(calls.length,beforeRepeatSync);
  previewResult={...previewResult,counts:{additions:0,changes:0,extras:0,local_files:3},additions:[],changes:[],extras:[]};await run('compareDeck()');
  assert.match(node('deck-comparison').innerHTML,/No transfer is needed/);assert.equal(node('sync-now').disabled,true);
  actionCard('sync-now',4,'done',/Selected setup matches/);
  assert.match(node('deck-preview').innerHTML,/Compare again/);assert.doesNotMatch(node('deck-comparison').innerHTML,/id="sync-now"/,'results never add a second Sync control');
  const beforeZeroSync=calls.length;await assert.rejects(run('syncDeck()'),/No transfer is needed/);assert.equal(calls.length,beforeZeroSync);
  previewResult={...previewResult,unsupported:['game/custom.dll']};await run('compareDeck()');
  actionCard('sync-now',4,'waiting',/No transfer needed · review any custom files/);
  assert.doesNotMatch(node('sync-now').innerHTML,/Selected setup matches/,'unsupported selected files prevent match claims');
  protonResult={configured:false,loader_installed:true,prefix:'/fixture/prefix'};
  previewResult={...previewResult,unsupported:[],counts:{additions:1,changes:0,extras:0,local_files:3},additions:['new.dll']};await run('compareDeck()');
  previewResult=Error('Game versions differ after installation.');await assert.rejects(run('configureDeckProton(true)'),/versions differ/);
  assert.equal(context.comparison,null,'a failed automatic recompare discards the old pre-install plan');
  assert.equal(node('sync-now').disabled,true,'installation success cannot bypass a failed fresh game-version check');
  const configsOnly={mods:false,configs:true,approvals:false,loader:false,game_settings:false};
  let finishSaving;syncOptionsResult=new Promise(resolve=>finishSaving=resolve);
  for(const [key,value] of Object.entries(configsOnly))node('deck-sync-'+key).checked=value;
  run('comparison={digest:"old",game_version:{matched:true,build_id:"12345"}};deckSyncResult={result:{parity:true}}');
  const saving=run('changeDeckSyncOptions()');
  assert.equal(context.comparison,null,'changing scope immediately invalidates comparison');assert.equal(run('deckSyncResult'),null,'changing scope clears completed parity');
  assert.equal(node('deck-preview').disabled,true);assert.equal(node('sync-now').disabled,true,'busy scope save locks Compare and Sync');
  state.settings.deck_sync_options={mods:true,configs:true,approvals:true,loader:true,game_settings:false};await context.refresh();
  assert.equal(node('deck-sync-mods').checked,false,'a general refresh cannot replace pending choices');assert.equal(node('deck-sync-configs').checked,true);
  finishSaving({options:configsOnly});await saving;syncOptionsResult=undefined;
  assert.equal(node('deck-preview').disabled,false);assert.match(node('deck-sync-options-summary').textContent,/^mod configs$/);
  protonResult=Error('Proton not ready');state.loader_installed=false;run('resetDeckProton()');
  previewResult={digest:'configs-only',options:configsOnly,game_version:{matched:true,build_id:'12345'},counts:{additions:0,changes:1,extras:0,local_files:1},changes:['game/BepInEx/config/fixture.cfg'],unsupported:[],warnings:[]};
  const beforeConfigCompare=calls.length;await run('compareDeck()');
  assert.deepEqual(calls.slice(beforeConfigCompare).map(([action])=>action),['deck-preview'],'config-only comparison skips irrelevant Proton checks');
  assert.deepEqual(calls.at(-1)[1].options,configsOnly);assert.equal(node('sync-now').disabled,false,'config-only sync does not require the PC or Deck loader');
  actionCard('deck-proton-setup',3,'done',/Selected groups can sync without loader setup/);
  assert.match(node('deck-comparison').innerHTML,/Selected: mod configs\. Unselected groups stay unchanged/);
  const beforeConfigSync=calls.length;await run('syncDeck()');
  assert.deepEqual(calls.slice(beforeConfigSync).map(([action])=>action),['deck-sync'],'config-only sync skips loader checks');
  assert.deepEqual(calls.at(-1)[1],{digest:'configs-only',options:configsOnly});assert.doesNotMatch(node('deck-comparison').innerHTML,/matching managed mod files/,'partial sync never claims complete mod parity');
  syncOptionsResult=Error('Settings are read-only');node('deck-sync-configs').checked=false;node('deck-sync-approvals').checked=true;
  await assert.rejects(run('changeDeckSyncOptions()'),/read-only/);await context.refresh();
  assert.equal(node('deck-sync-approvals').checked,true);assert.equal(node('deck-sync-configs').checked,false,'failed saving keeps the user’s requested choices');
  assert.equal(node('deck-sync-options-save').hidden,false);assert.equal(node('deck-preview').disabled,true,'unsaved choices cannot compare');
  assert.match(node('deck-sync-options-status').textContent,/Choices were not saved/);
  syncOptionsResult=undefined;await run('saveDeckSyncOptions()');assert.equal(node('deck-sync-options-save').hidden,true);
  for(const key of ['mods','configs','approvals','loader','game_settings'])node('deck-sync-'+key).checked=false;
  await run('changeDeckSyncOptions()');assert.equal(node('deck-preview').disabled,true);assert.equal(node('sync-now').disabled,true);
  assert.match(node('deck-sync-options-status').textContent,/Choose at least one group/);
  const beforeEmptyCompare=calls.length;await assert.rejects(run('compareDeck()'),/Choose at least one sync group/);assert.equal(calls.length,beforeEmptyCompare,'empty choices never call preview');
  node('deck-sync-game_settings').checked=true;await run('changeDeckSyncOptions()');
  previewResult={...previewResult,digest:'preferences-only',options:{mods:false,configs:false,approvals:false,loader:false,game_settings:true},changes:['settings/game-preferences.json']};
  await run('compareDeck()');assert.equal(node('sync-now').disabled,false,'preference-only differences unlock Sync');
  assert.match(node('deck-comparison').innerHTML,/Game preferences \(audio &amp; language\)/,'synthetic preference transfer names use a friendly description');
  assert.match(node('deck-comparison').innerHTML,/Selected: game preferences/);await run('syncDeck()');
  assert.match(node('deck-comparison').innerHTML,/selected setup matches/);assert.match(node('deck-comparison').innerHTML,/selected items verified/);
  node('deck-sync-game_settings').checked=false;
  node('deck-sync-mods').checked=true;await run('changeDeckSyncOptions()');
  protonResult={configured:true,loader_installed:false,prefix:'/fixture/prefix'};
  previewResult={...previewResult,digest:'mods-only',options:{mods:true,configs:false,approvals:false,loader:false,game_settings:false}};await run('compareDeck()');
  assert.equal(node('sync-now').disabled,true,'mods-only cannot omit loader files on an unprepared Deck');assert.match(node('deck-status').textContent,/Include BepInEx & loaders/);
  protonResult.loader_installed=true;await run('compareDeck()');assert.equal(node('sync-now').disabled,false,'mods-only uses the existing Deck loader without requiring the PC runtime to be selected');
  for(const key of ['mods','configs','approvals','loader','game_settings'])assert.equal((html.match(new RegExp(`id="deck-sync-${key}"`,'g')) || []).length,1,'each sync category has one checkbox');
  assert.match(html,/Audio, language and voice settings\. Deck display and controls stay unchanged/);
  for(const id of ['deck-connect','deck-preview','deck-proton-setup','sync-now'])assert.equal((html.match(new RegExp(`id="${id}"`,'g')) || []).length,1,'the grouped actions have one static control each');
  const workflowMatch=html.match(/<div\b[^>]*\bid="deck-checklist"[^>]*>([\s\S]*?)<\/div>/);
  assert.ok(workflowMatch,'the top progress group contains the action buttons');
  assert.match(workflowMatch[0],/class="deck-main-actions" role="group" aria-label="Steam Deck workflow"/);
  const workflowIds=[...workflowMatch[1].matchAll(/<button\b[^>]*\bid="([^"]+)"/g)].map(match=>match[1]);
  assert.deepEqual(workflowIds,['deck-connect','deck-preview','deck-proton-setup','sync-now'],'the progress cards themselves are the single ordered workflow controls');
  const deckPage=html.match(/<section id="page-deck"[\s\S]*?<\/section>/)[0];
  assert.equal((deckPage.match(/class="deck-main-actions"/g) || []).length,1,'there is no duplicate lower workflow button row');
  assert.ok(deckPage.indexOf('id="deck-checklist"')<deckPage.indexOf('id="deck-settings"'),'action cards remain above the connection settings');
  assert.throws(()=>run('compareView({game_version:{matched:false}})'),/not verified/);
  console.log('Guided profile and Deck UI checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
